### ISSUE TITLE
Interested in moving this to the swaywm org?

### ISSUE THREAD

**Issue by ddevault** [sdilts/cl-wlroots#1]
Hey, thanks for working on a new wlroots wrapper! We keep a lot of these in the swaywm org, which helps with visibility when people are looking for a wrapper to use. Are you open to moving this there as well?

**Comment by sdilts** [comment]
I'd be open to doing that. What would I need to do?

**Comment by ddevault** [comment]
You'd need to go to https://github.com/sdilts/cl-wlroots/settings and hit "Transfer" at the bottom, then put in swaywm as the destination. Then I'll add you to the swaywm org and grant admin rights over the repo.

**Comment by ddevault** [comment]
Got your permissions set up. Thanks!
